### ISSUE TITLE
Performance comparison of Aarch64 context switch

### ISSUE THREAD

**Issue by cjhackillinois** [Qthreads/qthreads#101]
Do a timing test to see the performance difference between using Aarch64 native context switching assembly vs the ucontext.h library.

Process I follow:

1. Make change to `config/qthread_check_swapcontext.m4` file
2. Clean, configure, make, and install library
3. Check library using `objdump -d <library file> | grep qt_get` for appropriate functions based on using or not using library
4. Compile stress test `make task_spawn` inside the tests/stress folder. The executable is placed inside the `.libs` folder.
5. Do 3 timing tests
6. Paste picture

**Comment by cjhackillinois** [comment]
Branch: PRTestBranchDec2021

Inside the file: `config/qthread_check_swapcontext.m4` the parameter `qt_host_based_enable_fastcontext` enables the code to select assembly if the values is set to 'yes' and ucontext.h library if the value is set to 'no'

**Comment by janciesko** [comment]
Yes - this should apply equally to x86 and Power ISA.

**Comment by cjhackillinois** [comment]
@janciesko any particular timing test to use?

**Comment by janciesko** [comment]
Yes - I'll add one in a moment for context switching based on stress/taskspawn.c. For locking, I would probably benchmark with qthreads/test/stress/lock_acq_rel.c (PRTestBranchDec)

**Comment by janciesko** [comment]
Chris, if you have a moment, could you take a look at https://github.com/pmodels/argobots/tree/main/src/arch/fcontext.
I'd be interested to know how this asm implementation compares to ours, just ideologically.

**Comment by cjhackillinois** [comment]
@olivier-snl passed along that repo to me. From what I can tell, they don't save as many general-purpose registers. They also save some floating-point registers.  They also use the stack pointer for storing state while our code uses malloc-created (I believe) pointers. So it appears their code is swapping stack frames and preserving certain registers across the swap--appears to not be a full context switch. We are doing a full context switch, but don't preserve any FP registers.

**Comment by cjhackillinois** [comment]
Using ucontext library:

![image](https://user-images.githubusercontent.com/47911162/146433664-b5049359-9469-4759-9b87-f9d2103029f2.png)

Using native ARMv8 code:

![image](https://user-images.githubusercontent.com/47911162/146433744-aa2ebbe3-f767-4a0c-8570-e565d1edc423.png)

**Comment by cjhackillinois** [comment]
I merged 'main' into the 'fast-context' branch. I've ran a clean build and finished with a `make check`. All tests pass except the qutil test. However, even that tests passes sometime. So there may be a minor bug, but not sure.

![image](https://user-images.githubusercontent.com/47911162/149389333-742d481b-33a6-4492-9a2f-bc6259ca5ccd.png)

**Comment by janciesko** [comment]
I'll try to reproduce.

**Comment by cjhackillinois** [comment]
I added an image above to show my environment.
