### ISSUE TITLE
Install issues on Alpine Linux

### ISSUE THREAD

**Issue by olivier-snl** [Qthreads/qthreads#104]
Testing of Chapel on Alpine Linux revealed some install issues, and the Chapel team alerted us about them.  The related Chapel issue is https://github.com/chapel-lang/chapel/issues/19404

At minimum, there seems to be a problem related to the required headers for ssize_t (the signed size_t type) in this Linux distro.

We should install Alpine Linux in a container somewhere and investigate further.

**Comment by olivier-snl** [comment]
@janciesko This is the issue I mentioned to you yesterday.

**Comment by bradcray** [comment]
@janciesko , @olivier-snl : @mppf posted a proposed simple fix for the issue here:  https://github.com/chapel-lang/chapel/issues/19404#issuecomment-1080947570  (essentially adding missing `#include` files)

**Comment by janciesko** [comment]
PR: https://github.com/Qthreads/qthreads/pull/105

**Comment by bradcray** [comment]
Thanks, Jan!
