### ISSUE TITLE
CI failing in qthread_stackleft

### ISSUE THREAD

**Issue by janciesko** [Qthreads/qthreads#126]
We have CI failing in qthread_stackleft

**Comment by janciesko** [comment]
CI is failing with `thread2: Assertion: foo < left failed.`

It seems that gcc 11.3 has trouble with a `static  __attribute__((noinline))` function qualifier. It seems that removing the `static` qualfiier makes the error go away.

**Comment by olivier-snl** [comment]
> CI is failing with `thread2: Assertion: foo < left failed.`
> 
> It seems that gcc 11.3 has trouble with a `static __attribute__((noinline))` function qualifier. It seems that removing the `static` qualfiier makes the error go away.

Any indication why it doesn't like that combo?

**Comment by janciesko** [comment]
Closing.
