### ISSUE TITLE
Releases cannot be downloaded any more

### ISSUE THREAD

**Issue by eschnett** [Qthreads/qthreads#27]
It seems Googlecode has stopped serving tarballs for download; I am redirected multiple times, and in the end only see a pointer to Github. Github has 0 releases for download.

**Comment by olivier-snl** [comment]
Thanks for bringing this to our attention. Sandia hasn't allowed us to use Googlecode for a long time for legal reasons, so I'm surprised that it was still serving up Qthreads content up to now.  The releases are in github as separate branches, if you are looking for a particular one.  In the last few years we have only been putting stable/mature work into the master branch, so we have had many customers just use that, but we are looking at doing more regular releases again, and the lack of a ready-made tarball as you have pointed out is one good reason to pursue that course.

**Comment by eschnett** [comment]
The main advantage of a tarball would be that one doesn't need to have autotools installed to build it.

**Comment by stelleg** [comment]
@eschnett I've created a release tarball / tag from the 1.10 branch, and added a default configure so you don't need autotools

**Comment by eschnett** [comment]
@stelleg I don't think this `configure` works:
```
==> './configure' '--prefix=/Users/eschnett/src/spack-qthreads/opt/spack/darwin-elcapitan-x86_64/gcc-6.1.0-spack/qthreads-1.10-e6rq2xlgkdsr4adqagzu2aydjzrf2t3h' '--enable-guard-pages' '--with-topology=hwloc' '--with-hwloc=/Users/eschnett/src/spack-qthreads/opt/spack/darwin-elcapitan-x86_64/gcc-6.1.0-spack/hwloc-1.11.3-qpc4ubmu6e5jeok2ry7x2rqvwtlrtzws'
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
```

**Comment by stelleg** [comment]
@eschnett You're right, my fault. Working on a fix.

**Comment by eschnett** [comment]
When I run `./autogen.sh` as before, then I find:
```
checking for sys/syscall.h... yes
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in include/qthread/qthread-int.h (assuming C99 compatible system)
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether /Users/eschnett/src/spack-qthreads/lib/spack/env/gcc/gcc supports __FUNCTION__... yes
checking whether /Users/eschnett/src/spack-qthreads/lib/spack/env/gcc/gcc supports __func__... yes
checking cacheline width... 64
checking size of pthread_mutex_t... 64
checking size of void *... 8
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for C/C++ restrict keyword... __restrict
checking for working volatile... yes
checking for thread local storage (TLS) class... __thread
./configure: line 23674: syntax error near unexpected token `fi'
./configure: line 23674: `fi'
```

**Comment by stelleg** [comment]
Sorry @eschnett, had a bit of a brain fart.

I've followed jemalloc's approach of using github releases and just adding the dist build as a separate tarball. https://github.com/Qthreads/qthreads/releases still shows the source, but above that shows the .bz2 tarball which should be build-able without autotools.

**Comment by eschnett** [comment]
I confirm that this tarball works as intended.

**Comment by stelleg** [comment]
Thanks @eschnett, I'll close this now, but if you are anyone else has issues with the distribution tarball please comment here and I can re-open.
