### ISSUE TITLE
error: identifier "uint64_t" is undefined

### ISSUE THREAD

**Issue by jeffhammond** [Qthreads/qthreads#29]
I experienced this issue on `bowman.sandia.gov` with Intel 16.0.3 compilers, on the off chance you need to reproduce it.
# Error

```
[jrhammo@node03 benchmarks]$ icc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../test/benchmarks -I../../include -I../../include/qthread  -I../../../include -I../../../test/   -g -O2 -MT generic/time_gcd.o -MD -MP -MF $depbase.Tpo -c -o generic/time_gcd.o ../../../test/benchmarks/generic/time_gcd.c
In file included from ../../../test/benchmarks/generic/time_gcd.c(8):
../../../include/qt_gcd.h(43): error: identifier "uint64_t" is undefined
      uint64_t largeA = a;
      ^

In file included from ../../../test/benchmarks/generic/time_gcd.c(8):
../../../include/qt_gcd.h(44): error: identifier "uint64_t" is undefined
      uint64_t largeB = b;
      ^

compilation aborted for ../../../test/benchmarks/generic/time_gcd.c (code 2)
```
# Solution

Because this is trivial, I don't think it's worthwhile to submit a pull request.

```
[jrhammo@node03 benchmarks]$ git diff ../../../include/qt_gcd.h
diff --git a/include/qt_gcd.h b/include/qt_gcd.h
index 830e852..5f8736a 100644
--- a/include/qt_gcd.h
+++ b/include/qt_gcd.h
@@ -2,6 +2,8 @@
 # include "config.h"
 #endif

+#include <stdint.h>
+
 static QINLINE size_t qt_gcd(size_t a, size_t b)
 {
 #ifdef QTHREAD_SHIFT_GCD
```
# Commentary

Technically there should be a configure test for this type, since it is not guaranteed to exist.

**Comment by olivier-snl** [comment]
Thanks, Jeff.  Change committed directly to master.

**Comment by ronawho** [comment]
@olivier-snl I commented on your [commit](https://github.com/Qthreads/qthreads/commit/517dd3da754f87577dd6f47ad405c2c218971fab), but I can never remember if github notifies about comments on commits -- I think want to do `#include "qthread-int.h"` instead, which is effectively a configure generated wrapper around `#include <stdint.h>`

**Comment by olivier-snl** [comment]
@ronawho You are probably right.  I think I forgot about that file since it doesn't exist until after configure.  Bigger problem technically as pointed out by @jeffhammond is that the type may actually not be supported, particularly on 32-bit machines.

**Comment by ronawho** [comment]
[ax_create_stdint_h.m4](https://www.gnu.org/software/autoconf-archive/ax_create_stdint_h.html) (the thing that makes qthread-int.h) does a pretty good job of making sure `uint64_t ` is found if it's availble on a machine. qthreads uses `uint64_t` a bunch of other places anyways, so if it's truly not availble, a lot more than just `qt_gcd` is going to break

**Comment by olivier-snl** [comment]
So yes, we use uint64_t over a hundred times.

**Comment by m3m0ryh0l3** [comment]
`uint64_t` is a standard, mandatory part of the C99 spec, which is nearly twenty years old now. It's required to be supported on 32-bit machines by the C standard. Now, the memory-model semantics of a 64-bit integer may change (e.g. reads and writes may not be atomic), but that's because C99 didn't specify a memory model. Qthreads *already* requires that your compiler supports the C99 spec, so I don't think it's unreasonable to rely on the existence of `uint64_t`.

**Comment by m3m0ryh0l3** [comment]
Actually, since Qthreads requires support of C99, we can probably remove the reliance on ax_create_stdint.h - that's an ancient file from back in the early 2000's when compilers were likely to not have C99 support. Checking for stdint.h separately is redundant with the requirement of C99.

**Comment by jeffhammond** [comment]
@m3m0ryh0l3 I can't find the text that requires 64-bit fixed-width integer types, either in C11 or in POSIX.

From N1570:
> **7.20.1.1 Exact-width integer types**
> 1 The typedef name intN_t designates a signed integer type with width N , no padding 
> bits, and a two’s complement representation. Thus, int8_t denotes such a signed 
> integer type with a width of exactly 8 bits.
> 2 The typedef name uintN_t designates an unsigned integer type with width N and no 
> padding bits. Thus, uint24_t denotes such an unsigned integer type with a width of 
> exactly 24 bits.
> 3 These types are optional. However, if an implementation provides integer types with 
> widths of 8, 16, 32, or 64 bits, no padding bits, and (for the signed types) that have a 
> two’s complement representation, it shall define the corresponding typedef names.

Note the "These types are optional."

From http://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html:
> If an implementation provides integer types with width 64 that meet these requirements, 
> then the following types are required: int64_t uint64_t

**Comment by jeffhammond** [comment]
Also, the notion that checking for C99 is sufficient to test for the function of all of its required features is hilarious.  Have you ever used real compilers? 😜

**Comment by m3m0ryh0l3** [comment]
Yes, I've used real compilers... the efficacy of "checking for C99" is that it depends on what you check to see if you have C99 support. Obviously it's insufficient to simply check whether the compiler spits out an error when you give it the `-std=c99` argument (or something similar). The check for C99 that Qthreads uses (which is borrowed from autotools) is comprehensive, and tests a bunch of different C99 features. It doesn't check them all, but it DOES check for appropriate handling of 64-bit constants. I suppose I'm assuming that if the preprocessor handles 64-bit constants, then that means the compiler provides integer types with width 64, which means that `uint64_t` is both required and trivial to implement. In practice, I'd be surprised it a compiler's preprocessor could handle 64-bit math while the compiler itself did not provide uint64_t. That said, of course, you're right, it's not explicitly checked for, and compilers do violate the spec on occasion. The easiest thing to do is to leave the ax_create_stdint_h macro in place, if you think it's a realistic possibility.

**Comment by jeffhammond** [comment]
@m3m0ryh0l3 Ah ok, I wasn't sure what the test was.  The GCC folks loves to lie with `__STDC_VERSION__` and similar, so I have learned to be skeptical.  And just to be clear, I know that you've used plenty of real compilers - I was only teasing.

**Comment by npe9** [comment]
@jeffhammond  Is this resolved? If so I'll close it.

**Comment by jeffhammond** [comment]
I have not verified but https://github.com/Qthreads/qthreads/commit/517dd3da754f87577dd6f47ad405c2c218971fab should have done it.
