### ISSUE TITLE
Don't unconditionally #define restrict

### ISSUE THREAD

**Issue by dylan-stark** [Qthreads/qthreads#4]
# Reported by schnetter, Nov 17, 2014

I am building qthreads with clang++, and I am passing `-Drestrict=__restrict__` on the command line. This leads to the following warnings from qthrads:

    /Users/eschnett/SIMFACTORY/qthreads-1.10/install/include/qthread/common.h:87:9: warning: 
          'restrict' macro redefined [-Wmacro-redefined]
    #define restrict __restrict

You could add an #ifdef around this #define, so that the user's preference takes precedence.

**Comment by m3m0ryh0l3** [comment]
I think the real question, IMHO, is "why would you do that?" I mean, the qthreads source is not meant to be source-compatible with C++ in any form. It uses several C99 features that either do not exist in C++ (e.g. compound literals) or exist in incompatible forms (e.g. variable-length arrays and variadic macros). Thus, building qthreads with a C++ compiler is not something I would expect to work. However, I get the feeling you're trying to achieve something by compiling it this way, and I wonder what that is. Maybe there's a better solution? (perhaps not enough of the headers have "extern C {}" declarations in them to link nicely with your C++ code?)

**Comment by eschnett** [comment]
Sorry, the first sentence in my bug report is wrong.

I'm not building qthreads with a C++ compiler -- I'm including its header files <qthread/qthread.hpp> and <qthread/qt_syscalls.h> into C++ code, after having built qthreads the regular way.

**Comment by npe9** [comment]
Hey @eschnett, I've applied your patch. Please tell me if that works for you.
