### ISSUE TITLE
Add support for custom memory allocators

### ISSUE THREAD

**Issue by ronawho** [Qthreads/qthreads#40]
Qthreads currently just calls down to the system malloc and friends, but we'd like to be able to specify custom allocators.

There's two motivating reasons for us:

 * The main one is that with multi-locale programs we register our heap with the NIC for fast one sided communication. We have to bounce/trampoline memory that's allocated from the system, which can hurt performance when communicating things that are on qthread stacks. If we could have qthreads grab memory from our shared heap (by calling our allocator routines) that should have nice performance benefits for us and allow us to allocate more space for the heap without worrying about needing to leave some memory for qthreads to use.

 * We use jemalloc as our default allocator, and generally speaking it's significantly faster for concurrent allocations than the system allocator. This probably won't have a huge speed benefit for qthreads since most memory is pooled, but it could still improve performance for unpooled memory, or even for allocating pools in the first place.

I don't think we have any preference for the mechanism for overriding. Could be a configure time thing, or a execution time choice (maybe something like what [GMP does](https://gmplib.org/manual/Custom-Allocation.html))

This is a medium priority for us. It'd be nice and should help performance, but it's not blocking anything for us.

**Comment by ronawho** [comment]
I think you've already started on this with 0598718f89087bc6740b926c328c09ee15c7b9a3, but it wasn't obvious to me if that's the final solution, or just something you were experimenting with.

**Comment by npe9** [comment]
If you don't mind support a MALLOC and FREE api it's already done. If you need a custom API I'll be happy to integrate that too.

**Comment by ronawho** [comment]
Ok cool, I'll try that out (maybe early next week) and get back to you

**Comment by ronawho** [comment]
Getting segfaults when I try this out. I'm guessing there's some case where `MALLOC` is being used to allocate but regular `free` is being used to deallocate or something. 

For instance it looks like `MALLOC` is used to allocate memory pools, but then `realloc` calls are made.

There seems to be a lot of naked called to `malloc`, `calloc`, `free`, and `realloc` in the codebase. Beyond wrapping those, it looks like you'll want to add wrappers for realloc and calloc, and maybe even an aligned alloc too.

**Comment by ronawho** [comment]
And FYI in our runtime code we define malloc, calloc, realloc, and free to garbage values to prevent us from accidentally using them. It's not perfect, but it's worked pretty well for us so far: 

https://github.com/chapel-lang/chapel/blob/master/runtime/include/chpl-mem-warning-macros.h

**Comment by npe9** [comment]
Gotcha, what build options should I use to reproduce the bug?

**Comment by ronawho** [comment]
Here's a pointer to my branch: https://github.com/ronawho/chapel/tree/use-chpl-alloc-for-qt

Note that it did require me to modify qthreads source in order to add an include for our memory layer header. I can't think of a good way to avoid that, so it's not obvious how to make 0598718f89087bc6740b926c328c09ee15c7b9a3 work without additional mods to qthreads. Any thoughts?

Also, it might be easier to debug and test a standalone qthreads outside of chapel. i.e override MALLOC and FREE with calls to je_malloc and je_free and see what breaks for qthreads tests. Could either build jemalloc from source, or just give include/lib paths to the version that lives inside the chapel repo.

**Comment by npe9** [comment]
@ronawho do you actually need to modify the source on the qthreads side of things? Qthreads could provide a header that makes it possible to give qthreads customer allocators that adhere to  its signatures. That solves the dependency chain chapel (qthreads user) -> qthreads (chapel allocator user) -> chapel.

For the moment the contract is just implicit, in qthreads the symbols are undefined and whatever's linking qthreads should provide the symbols.

I'll also try with je_malloc and add some tests, because external allocators will be easy to break if people aren't careful.

Is there something I'm missing?

**Comment by ronawho** [comment]
Ah, I suppose it might have worked if I just left the symbols be undefined at build time, but I didn't actually try that out

**Comment by ronawho** [comment]
Right, the external allocator thing is super easy to break because it's really easy to just call malloc/calloc/realloc/free without thinking about it. 

FWIW that's why we have https://github.com/chapel-lang/chapel/blob/master/runtime/include/chpl-mem-warning-macros.h, because we made this mistake so many times ourselves.

**Comment by ronawho** [comment]
Bumping the priority of this for us -- I hackily got this working on https://github.com/ronawho/chapel/tree/use-chpl-alloc-for-qt and it actually has really significant performance improvements for ugni+qthreads. 

In fact with it, ugni+qthreads outperforms ugni+muxed (or proprietary tasking layer that we'd like to retire) in all cases. It resulted in 2X speedup for MiniMD and FFT and a ~25% speedup for HPL. It's possible it positively impacted more tests too, but those were the cases where qthreads was losing before so those are the ones I looked at.

Think I said this in the description, but the reason this helps with multi-locale is because it means qthread stacks are now in our registered heap, so we can do fast one-sided communication without having to trampoline/bounce through a registered page.

This doesn't really seem to impact single-locale performance, which isn't too surprising since qthreads uses memory pools for most hot spots anyways: http://chapel.sourceforge.net/perf/chapcs/qtChplAlloc/

**Comment by ronawho** [comment]
And after playing with it some more, I'm not loving the define API, it feels pretty clunky to me

I think my preference would be for having a qt_alloc header that declares/defines 

qt_alloc
qt_calloc
qt_realloc
qt_free
qt_aligned_alloc
qt_aligned_free

and having a configure option that allows you to specify a different header to use. 
I think this is what you were suggesting with:

>Qthreads could provide a header that makes it possible to give qthreads customer allocators that adhere to its signatures. That solves the dependency chain chapel (qthreads user) -> qthreads (chapel allocator user) -> chapel.

And FWIW: The current API feels weird to be because it's using macros for some allocation routines, but aligned alloc/free live in their own file. It also seems weird to include qt_debug in order to get a hold of the MALLOC/FREE wrappers instead of including something like qt_alloc.h. Using static inline functions over macros would also allow you to use something like pycparser to "grep" the code base for calls to malloc, calloc, valloc, realloc, free, aligned_alloc, posix_memalign, and memalign to ensure that this feature doesn't get broken by a stray call to the system allocator

**Comment by npe9** [comment]
The custom-alloc branch will compile and run hello world with the chpl_malloc allocators but it complains about not finding the symbols in the compile phase. @ronawho If you get a chance I'd like to get your help fixing the warnings.

**Comment by ronawho** [comment]
Think you were just missing the `#include "chpl-mem-impl.h"`

I have a branch trying it out -- https://github.com/chapel-lang/chapel/compare/master...ronawho:use-chpl-alloc-for-qt-2

First two commits just switch to using the custom-alloc branch, the 3rd one is the important one. 

The hellos compile and work for with `CHPL_MEM=cstdlib` which just maps things down to the system allocator, but there's still places in qthreads calling the system alloctor so we're getting mismatched calls to je_malloc and the system free (and things like that) for `CHPL_MEM=jemalloc`

**Comment by ronawho** [comment]
Pushed 2 new commits to that branch, and it's testing cleanly with `CHPL_MEM=jemalloc` for our entire suite

Changes are: 
 - have MALLOC/FREE wrappers call down to qt_malloc and qt_free
 - inline aligned_alloc.c into base.c and provide aligned alloc/free implementations for chapel.c 

Still plenty of cleanup needed, but it's passing testing

**Comment by npe9** [comment]
@ronawho I believe with the inclusion of custom allocators in the previous release we can close this issue?

**Comment by ronawho** [comment]
I think this needs some sort of validation/testing to ensure that calls to the system allocator aren't mistakenly introduced in the future. In https://github.com/Qthreads/qthreads/issues/40#issuecomment-267714368 I mentioned that we used to define malloc/free to bogus things, but we recently switched over to a script that effectively greps for calls to the system allocator, and you're more than welcome to use that.

To try it out you can do:



```bash
git clone git@github.com:Qthreads/qthreads.git
cd qthreads/
wget https://raw.githubusercontent.com/chapel-lang/chapel/master/util/devel/look_for_alloc.py
python look_for_alloc.py --exclude-paths=test,src/alloc/base.c
```

```sh
mbp-eronagha: qthreads (master) $ python look_for_alloc.py --exclude-paths=test,src/alloc/base.c
Error: found call to "calloc"
qthreads/include/qt_threadqueue_stack.h qt_stack_create 27 stack->storage = calloc(capacity, sizeof(qthread_t*));
qthreads/include/qt_threadqueue_stack.h qt_stack_resize 64 qthread_t **storage = calloc(2 * old_capacity, sizeof(qthread_t*));

Error: found call to "free"
qthreads/include/qt_threadqueue_stack.h qt_stack_free 36 free(stack->storage);
qthreads/include/qt_threadqueue_stack.h qt_stack_resize 75 free(old_storage);

Error: found call to "posix_memalign"
qthreads/src/threadqueues/loxley_threadqueues.c qt_threadqueue_new 89 posix_memalign((void **)&q, 64, sizeof(qt_threadqueue_t));
qthreads/src/threadqueues/loxley_threadqueues.c qt_threadqueue_new 99 posix_memalign((void **)&q->local[i], 64, sizeof(qt_threadqueue_local_t));
qthreads/src/threadqueues/loxleybase_threadqueues.c qt_threadqueue_new 59 posix_memalign((void **)&q, 64, sizeof(qt_threadqueue_t));
qthreads/src/threadqueues/nottingham_threadqueues.c qt_threadqueue_new 124 posix_memalign((void **)&q, 64, sizeof(qt_threadqueue_t));
qthreads/src/threadqueues/nottingham_threadqueues.c qt_threadqueue_new 138 posix_memalign((void **)&(q->base), 64, q->size * sizeof(m128i));
qthreads/src/threadqueues/nottingham_threadqueues.c qt_threadqueue_new 139 posix_memalign((void **)&(q->rwlock), 64, sizeof(rwlock_t));
qthreads/src/threadqueues/nottingham_threadqueues.c qt_threadqueue_resize 320 qassert(posix_memalign((void **)&(newloc), 64, newsize * sizeof(m128i)), 0);

Error: found call to "strdup"
qthreads/src/rcrtool/perf_util.c perf_setup_list_events 94 events = strdup(ev);
```

I would copy that script from us and commit it to the qthreads repo and run it as part of the travis smoke test. It requires cscope, but I'm pretty sure that's availble under travis.

**Comment by ronawho** [comment]
More on the style side, which is really up to you since it's your code, but I think there's some needed cleanup. I'm pretty sure I mentioned this over email so you can probably find more details there, but the things that I would still like to see are:

 - rename qt_internal_aligned_alloc/qt_internal_aligned_free to drop the "internal" part.
 - change aligned_alloc/free to use size_t instead of uint_fast16_t for alignment to match Chapel's/C11's aligned_alloc 

 * cleanup the base.c/chapel.c allocators. specifically removing the need to implement a getpagesize() and _pagesize and qt_internal_alignment_init. Ideally we'd only have to implement `qt_malloc, qt_free, qt_calloc, qt_realloc, qt_aligned_alloc, and qt_aligned_free`
 * Add a qt_getpagesize that uses `sysconf(_SC_PAGESIZE);` when available instead of getpagesize() since getpagesize is deprecated. Can probably reuse some of the code in the configure script that checks for a working mmap to implement sane fallbacks.
 * removing unnecessary `#include <stdlib.h>` that were just there to bring in malloc and friends (this one can be tricky in that you have to be careful to not remove the include from files that are using other stdlib functions. I've had good luck with cppclean or include-what-you-use in the past for this sort of cleanup.
 * The split usage of qt_malloc/qt_free and MALLOC/FREE wrappers is a little confusing, and it's never clear to me which one is appropriate. It'd be nice to unify this somehow. This is a long standing issue though, I just ran into it a lot while prototyping various external allocator implementations

**Comment by ronawho** [comment]
We've been using this successfully for a while. The cleanups mentioned above may still be nice, but the feature is working for us so I'm going to close this.
