### ISSUE TITLE
qthread_topo=no is not included in release

### ISSUE THREAD

**Issue by ronawho** [Qthreads/qthreads#58]
https://github.com/Qthreads/qthreads/commit/c194ff205 renamed `topo=no` to `topo=sys` and made `topo=no` just accept env vars but it does no topology detection itself. Looks like `topo=no` is no longer included in the release so a build from the release will fail. 

I think this should be as simple as re-adding `no` to the `EXTRA_DIST` topo list: 

```diff
diff --git a/src/Makefile.am b/src/Makefile.am
index 0382094c..d6150509 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -113,6 +113,7 @@ EXTRA_DIST += \
                         affinity/hwloc.c \
                         affinity/binders.c \
                         affinity/hwloc_v2.c \
+                        affinity/no.c \
                         affinity/sys.c \
                         affinity/libnuma.c \
                         affinity/libnumaV2.c \
```

Somewhat related, it looks like the autodetection of `topo=sys` isn't quite working. Looking at the log, it looks like `_SC_NPROCESSORS_CONF` support is detected, but topo still defaults to `no`:

https://travis-ci.org/Qthreads/qthreads/jobs/401820820#L720
https://travis-ci.org/Qthreads/qthreads/jobs/401820820#L752

I'm not quite sure what's going on there (and I could be wrong about sys support being detected). For me `topo=mach` is correctly autodetected on a mac, but `topo=sys` is not autodetected on linux.

**Comment by npe9** [comment]
@ronawho I incorporated your changes in commit 06a96dfe6f5234f0b25931eb65b1673e6583a926, I also pulled in the 'RUNTIME_DATA_SIZE' flag  that you guys are using in 0881911a9b6381623787eced58ec4c3b371989c7. This allows me to compile chapel with a regular 'make dist' tarball from a qthreads install.

'make check' on a pull of the Chapel tip works for me with these changes. If they work on your end I'll close this issue.

Also, we are prepping for a release by the end of September, if you guys have any other questions/comments.

**Comment by npe9** [comment]
@olivier-snl

**Comment by ronawho** [comment]
@npe9 cool, thanks!

We have a couple of other outstanding changes. If you want I can open PRs for those and you can decide if you want to accept them.

For this issue, I think it'd be nice to fix the auto-detection for `topo=sys`, but that's not really an important use-case for us so I'm ok closing this.

**Comment by npe9** [comment]
@ronawho sure send them on by. I'll check out the autodetection for the next release.
