### ISSUE TITLE
parallel make check hangs

### ISSUE THREAD

**Issue by stelleg** [Qthreads/qthreads#59]
I've noticed `make check -j4` hangs on the stress tests. I would imagine contention for cores would slow it down some, but it seems to hang completely. Haven't had a chance to dig into why.

**Comment by npe9** [comment]
I've seen this too. When we get the other kinks worked out we can dig into this. OSX just hangs in make check in general.

**Comment by janciesko** [comment]
Reproduced on Pow9. "sinc_workers"  seems to cause the hang. Investigating.

**Comment by janciesko** [comment]
@stelleg, could you retest this please and confirm which test fails?

**Comment by stelleg** [comment]
Looks like the following stress tests are hanging:

    task_spawn, test_spawn_simple, precond_spawn_simple, subteams_uts

I'm not 100% sure its deadlock and not slowdown, but those tests all finish in a couple seconds without parallel check, and hang for minutes with parallel.

**Comment by janciesko** [comment]
#57 - potentially relevant.

**Comment by olivier-snl** [comment]
> I ran `make check -j4` with this env: ![image](https://user-images.githubusercontent.com/47911162/137184645-62bd35f7-13c1-42c6-9ed9-03913d2c29aa.png)
> 
> Everything passes.
> 
> I notice hangs when I increase number of workers to 8 or above. It may be lower, but with a value of '2' everything passed.

Thanks.  What was the configure line for you build?
