### ISSUE TITLE
AC_INIT name is qthread instead of qthreads

### ISSUE THREAD

**Issue by npe9** [Qthreads/qthreads#64]
We're running into a naming problem when packaging qthreads for our new arm platform.

`make dist` produces the tarball `qthread-<version>` which is determined by the name defined in the initial `AC_INIT` in `configure.ac`. 

Would there be any objections from changing the `AC_INIT` name to qthreads rather than "qthread"?

@ronawho @m3m0ryh0l3

**Comment by ronawho** [comment]
I don't think this matters to us, but I'm also not sure I completely understand what this will change from our perspective.

**Comment by npe9** [comment]
Just the package name unless AC_INIT does more magic that I'm not aware of. @m3m0ryh0l3 might know more about the provenance of the naming.

**Comment by ronawho** [comment]
Ok, shouldn't impact us. Thanks for the heads up though

**Comment by npe9** [comment]
I just made the change in the tip. If necessary we can revert it.
