### ISSUE TITLE
Per-qthread TLS support for MPI integration

### ISSUE THREAD

**Issue by olivier-snl** [Qthreads/qthreads#66]
Need some sort of per-qthread TLS support in order to use Qthreads as an alternative to pthreads for the threading layer in Open MPI and/or MPICH.

**Comment by m3m0ryh0l3** [comment]
Is qthread_get_tasklocal() what you're looking for?

**Comment by olivier-snl** [comment]
@m3m0ryh0l3 Exactly why I created this issue: Figured you you would chime in if this was available and I had just not used it thus far.
