### ISSUE TITLE
MacOS Yosemite support

### ISSUE THREAD

**Issue by m3m0ryh0l3** [Qthreads/qthreads#7]
When running on MacOS Yosemite (10.10.1), it fails randomly in malloc (usually in qt_affinity_gendists) complaining about memory corruption if and only if QT_NUM_SHEPHERDS is > 6 (whether set manually, or determined by sysctl()).

**Comment by olivier-snl** [comment]
I just merged labnerd's pull request which I think should have resolved this problem.
