### ISSUE TITLE
Configure error with 1.16 release

### ISSUE THREAD

**Issue by eschnett** [Qthreads/qthreads#78]
Running `configure` fails with the error
```
configure: error: cannot find install-sh, install.sh, or shtool in config "/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-qthreads-1.16-c3c6zkpee4ergs2xdjmxdsjm3oipqvgm/spack-src"/config
```
The `config` directory of the 1.16 release contains symbolic links pointing to `/usr/share`. As a result, the symbolic links don't resolve. (I don't think a release tarball should contain symbolic links pointing to external files.)

This is probably caused by `autogen.sh` creating symbolic links instead of copying files.

Running `autogen.sh` manually also fails:
```
$ ./autogen.sh
Generating configure files...
LIBTOOLIZE=/opt/local/bin/glibtoolize
Since LIBTOOLIZE and ACLOCAL are in the same directory, I'm going to assume they know about each other.
aclocal: error: aclocal: file 'config/lt~obsolete.m4' does not exist
autoreconf: /opt/local/bin/aclocal failed with exit status: 1
It appears that configure file generation failed.  Sorry :(.
```

Things work fine with the 1.15 release.

**Comment by janciesko** [comment]
Thanks Erik for reporting, I have updated the package.

**Comment by eschnett** [comment]
This problem is now fixed.
