### ISSUE TITLE
1.16 release includes generated files

### ISSUE THREAD

**Issue by ronawho** [Qthreads/qthreads#80]
A generated config.h seems to be in the release. This causes build errors since whatever system that was generated on has different object sizes and different headers than the systems I'm running on.  e.g
 
```
In file included from include/qt_asserts.h:7:
include/config.h:638:9: warning: 'SIZEOF_PTHREAD_MUTEX_T'
      macro redefined [-Wmacro-redefined]
#define SIZEOF_PTHREAD_MUTEX_T 40
        ^
../include/config.h:638:9: note: previous definition is here
#define SIZEOF_PTHREAD_MUTEX_T 64

...

src/ds/qdqueue.c:14:11: fatal error: 'numa.h' file not found
# include <numa.h>
```

I also see some schedulers and other files that are not normally included in the releases. e.g. 

```
curl -sL https://github.com/Qthreads/qthreads/releases/download/1.15/qthread-1.15.tar.bz2 | tar -xvj
curl -sL https://github.com/Qthreads/qthreads/releases/download/1.16/qthread-1.16.tar.bz2 | tar -xvj

$ diff -qr qthread-1.15/src/threadqueues/ qthread-1.16/src/threadqueues/ | grep "Only in"
Only in qthread-1.16/src/threadqueues/: loxleybase_threadqueues.c
Only in qthread-1.16/src/threadqueues/: loxley_threadqueues.c
```

I'm not very familiar with the release process, but I think `make dist` removes the generated files and schedulers not meant for the release.

**Comment by ronawho** [comment]
FYI @janciesko

**Comment by janciesko** [comment]
Thanks for reporting. The distribution package should now be clean.

**Comment by ronawho** [comment]
Looks good now, thanks!
