### ISSUE TITLE
Build failure on Apple Silicon

### ISSUE THREAD

**Issue by carlocab** [Qthreads/qthreads#83]
I'm trying to get qthreads packaged for Homebrew (cf. https://github.com/Homebrew/homebrew-core/pull/73445), but I'm encountering the following build failure on the Apple Silicon CI node:

```
fastcontext/asm.S:46:4: error: What kind of a Mac is this?
#  error What kind of a Mac is this?
   ^
```

I get this same error whether I use the `configure` script in your release tarball, or run `autogen.sh` myself from the original source code.

Assistance would be appreciated.

**Comment by olivier-snl** [comment]
We have not yet added support for Arm macs, so thanks thanks for bringing this to our attention.  The error you are seeing occurs because Qthreads is trying to configure for the right kind of assembly code to do fast context switching, and it is not aware of such a thing as an Arm mac.
