### ISSUE TITLE
add support for hwloc symbol prefix

### ISSUE THREAD

**Issue by jhh67** [Qthreads/qthreads#86]
hwloc can be configured to add a prefix to all of its symbols via the `--with-hwloc-symbol-prefix` argument to `configure`.  The file `hwloc/rename.h` takes care of the renaming transparently by creating macros for all hwloc symbols so that no modifications are required to either the hwloc source code or the code that calls hwloc. As a result, unmodified qthreads will compile just fine using a hwloc library that has a custom prefix. The problem is in configuring qthreads. The following line from `qthread_check_hwloc.m4` fails to find the hwloc library because the symbol name lacks the prefix:
`	    [AC_SEARCH_LIBS([hwloc_topology_init], [hwloc "hwloc -lnuma"], [],
		                [qt_allgoodsofar=no])])`

It would work if the stub C file created by AC_SEARCH_LIBS were to #include hwloc.h, but I don't know how to make it do that. I propose creating a new argument `--with-hwloc-prefix=prefix` to the qthreads configuration so that `qthread_check_hwloc.m4` finds the hwloc library properly.

**Comment by olivier-snl** [comment]
If we go this route, it might be better to use --with-hwloc-symbol-prefix as the new Qthreads option as well, rather than --with-hwloc-prefix.  That would also help people to not be confused and think we are talking about a directory prefix.

However, the bigger question is how to go about the change.

**Comment by jhh67** [comment]
I have a prototype that adds the --with-hwloc-symbol-prefix argument, but it needs cleanup and testing.

**Comment by janciesko** [comment]
Great, feel free to drop a PR. Probably we need to conditionally replace AC_SEARCH_LIBS([hwloc_topology_init] and the test.
