### ISSUE TITLE
qt_connect sucess when expected to fail

### ISSUE THREAD

**Issue by king-11** [Qthreads/qthreads#88]
I have been working on a Socket Library for Chapel and planned to use `qt_syscalls` instead of the regular system calls. While `qt_select` and `qt_accept` seems to work fine. `qt_connect` returns a success even when the address it's provided to connect to has no service listening on it.

While using normal `connect` call a `115` errno is returned which is _Transport endpoint is not connected_ whereas `qt_connect` returns a `0`.

Reproducible code :

```c
#include <stdio.h>  //printf
#include <string.h> //strcpy
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <fcntl.h>
#include <stdlib.h>
#include <qthread/qt_syscalls.h>
#include <errno.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
  int socket_desc;
  int iport = 8000;

  //Create socket
  const int val_sock = AF_INET;
  socket_desc = socket(val_sock, SOCK_STREAM|SOCK_NONBLOCK, 0);
  if (socket_desc == -1)
  {
    printf("Could not create socket");
  }

  int flags = fcntl(socket_desc, F_GETFL, 0);
  fcntl(socket_desc, F_SETFL, flags | O_NONBLOCK);

  // fill in address
  struct sockaddr_storage x;
  memset(&x, 0, sizeof(x));
  struct sockaddr_in *x1 = (struct sockaddr_in *)&x;
  x1->sin_family = AF_INET;
  x1->sin_port = htons(iport);
  x1->sin_addr.s_addr = htonl(INADDR_LOOPBACK);

  // extract out data
  char address[NI_MAXHOST], port[NI_MAXSERV];
  int err = getnameinfo((struct sockaddr*)&x, sizeof(struct sockaddr_storage), address, sizeof(address), port, sizeof(port), NI_NUMERICHOST | NI_NUMERICSERV);
  puts(address);
  puts(port);

  int n;

  if ((n = qt_connect(socket_desc, (struct sockaddr *)&x, sizeof(x))) < 0)
  {
    if(errno != EINPROGRESS){
      puts(strerror(errno));
      exit(0);
    }
  }

  puts("connect tried");

  if(n == 0){
    printf("connect success");
    exit(0);
  }

  fd_set rset, wset;
  FD_ZERO(&wset);
  FD_ZERO(&rset);
  FD_SET(socket_desc, &rset);
  FD_SET(socket_desc, &wset);
  struct timeval tval;
  tval.tv_sec = 10;
  tval.tv_usec = 0;


  if((n = select(socket_desc + 1, NULL, &wset, NULL, &tval)) == 0){
    puts(strerror(ETIMEDOUT));
    exit(0);
  }
  puts("select tried");


  if(n < 0){
    puts(strerror(errno));
    exit(0);
  }
  puts("select error checked");


  if(FD_ISSET(socket_desc,&rset) || FD_ISSET(socket_desc, &wset)) {
    socklen_t len;
    if(getpeername(socket_desc, (struct sockaddr *)&x, &len) < 0){
      puts("peername fail");
      puts(strerror(errno));
      exit(0);
      if(errno == ENOTCONN){
        int err_t;
        socklen_t len = sizeof(err_t);
        if(getsockopt(socket_desc, SOL_SOCKET, SO_ERROR, &err_t, &len) < 0) {
          puts("getsockopt fail");
          close(socket_desc);
          puts(strerror(errno));
          exit(0);
        }
        if(err_t){
          close(socket_desc);
          puts(strerror(err_t));
          exit(0);
        }
      }
    }
  }
  else {
    close(socket_desc);
    puts("Select error: socketFd not set");
    exit(0);
  }
  puts("rset wset pass");


  printf("connect success");
}
```

Although I haven't been able to compile the C file in my own system I tried these same procedures using chapel's runtime and C interoperability.

**Comment by olivier-snl** [comment]
For reference, the last discussion of the qthreads syscalls API I could find was in this issue closed by @ronawho :
https://github.com/Qthreads/qthreads/issues/37

It was specifically about sleep calls, but included some discussion of about the general status and philosophy behind the qthreads system calls API.

**Comment by mppf** [comment]
@olivier-snl - have you been able to reproduce the problem? thanks.

**Comment by olivier-snl** [comment]
What I see with the code above:

```
127.0.0.1
8000
Segmentation fault (core dumped)
```

What I see if I switch to the system connect call:

```
127.0.0.1
8000
connect tried
select tried
select error checked
peername fail
Transport endpoint is not connected
```

This is on RHEL7 with gnu.

**Comment by olivier-snl** [comment]
Update:

The example above needs a call to qthread_initialize(), with include of <qthread/qthread.h>, to be a stand-alone reproducer.  Now I see output as you said:

```
127.0.0.1
8000
Success
```

**Comment by olivier-snl** [comment]
OK, folks.  I have a solution for this issue.  So what happens is that Qthreads sends off the system call to a queue and then gets it back, but in the mean time the errno is lost.  What we need to do is capture the value of errno (as we are already doing for the return value) and restore it.  I have prototyped this solution and successfully tested it with the example.

Now unfortunately I think that the issue applies to the other system calls as well, so that we will need to apply it to them too.

Follow up question though: Which other socket calls are you wanting to use?  When looking into this issue, I noticed that some frequently used ones appear in comments but have no existing "qt" implementation: send, sendto, recv, recvfrom.

**Comment by olivier-snl** [comment]
Branch with fix: https://github.com/Qthreads/qthreads/tree/syscall-fix-errno 

I will PR into main once I have a feel for what other related corrections are needed.

**Comment by olivier-snl** [comment]
I have applied the change across the other system calls, though I have not done additional testing beyond the test case you presented.

PR: https://github.com/Qthreads/qthreads/pull/89

**Comment by king-11** [comment]
Thanks a lot for such a quick response 😄

**Comment by olivier-snl** [comment]
The PR has been merged.  I'll leave this issue open a little longer in case there is other feedback on this issue from your testing.

**Comment by king-11** [comment]
I will close the PR as seems to work now if their are any other issues I will make sure to comment again thanks
